# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Qamardeen Abdul-Malik Oladimeji
title: Google Certified UX/UI designer
email: qamardeenabdulmalik@gmail.com
# email_title: Email (Email title override)
phone: +2347033484845
# phone_title: Phone (Phone title override)
website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: qamardeen02
github_username:  mkayfrenzy
stackoverflow_username: qamardeen abdul-malik oladimej
dribbble_username: qamardeen abdul-malik oladimeji
facebook_username: maleekfrenzy
flickr_username: 
instagram_username: qamar oladimeji
linkedin_username: in/qamardeen-abdul-malik-59577896
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username: 

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url qamardeenoladimeji.myportfolio.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  My name is Abdul-Malik, i am a gogle cerified UX/UI designer, even though i graduated from the department of Anatomy as the best graduating student,
  i delved into the world of UX diectly because that has always been my passion, and within that short period, i took several classes, and also enrolled
  for a master certificate in UX by google, Even though we never stop learning as a designer, i can confidently say i put my best into anything i embark 
  upon to make sure i get the best possible result.

  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Case Study for a shopping app called Shoptacle
        link: https://www.behance.net/gallery/142809049/Case-study-of-a-shopping-app-called-Shoptacle/modules/806825425
        link_text: Here is a link to the project
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://www.behance.net/gallery/142809049/Case-study-of-a-shopping-app-called-Shoptacle/modules/806825425
        quote: >
          Short overview of the project 
          An application design to allow customers of a clothing store shop online
        description: | # this will include new lines to allow paragraphs
          Shoptacle is a large clothing store, with several stores all over the country, they have a large collection of designer clothing and accessories.
          they stand for luxury effieciency, gonesty and customer satisfaction
   
  
  - title: Experience
    layout: list
    content:
      - layout: right
        title: De9ja spirit media
        sub_title: Content creator
        caption: Date Range (eg. january 2020 - november 2020)
        link: Link to company (optional)
        quote: >
          A media company that updates latest news, music, videos and stories 
        description: | # this will include new lines to allow paragraphs
          I worked there as a content creator where i published several SEO articles
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Osun state university
        sub_title: Bsc Anatomy
        caption: Date Range (eg. 2016- 2021)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
          
    content:
      - layout: top-right
        title: Osun state university
        sub_title: Bsc Anatomy
        caption: Date Range (eg. 2016- 2021)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
        
          
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
     TECHNICAL SKILLS - Figma, Adobe Xd, Microsoft Office, Invision studio, Adobe Premiere pro and Basic knowledge in Adobe photoshop.
     
     DESIGN skills - user research, wireframing, usability studies, presentation, prototyping
     
     Collaboration - communication, teamwork, detail oriented, strong presenter

     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-cayman
